# Generated by Django 5.1.3 on 2024-11-08 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('model_type', models.CharField(choices=[('regression', 'Regression'), ('classification', 'Classification'), ('clustering', 'Clustering')], max_length=20)),
                ('algorithm', models.CharField(choices=[('linear_regression', 'Linear Regression'), ('logistic_regression', 'Logistic Regression'), ('random_forest', 'Random Forest'), ('svm', 'Support Vector Machine'), ('kmeans', 'K-Means Clustering')], max_length=20)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trained', models.BooleanField(default=False)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('metrics', models.JSONField(default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etl.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
