# Generated by Django 5.1.3 on 2024-11-09 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='media/ml_models/'),
        ),
    ]
